num1 = input("Please enter the first number")
num1 = int(num1)
print()
num2 = input("Please enter the second number")
num2 = int(num2)
print()
print()
import random
randomnum = random.randint(num1,num2)
print("Random number in the range of numbers entered:")
print (randomnum)